### ISSUE TITLE
Add defaults for markdown

### ISSUE THREAD

**Issue by hax** [editorconfig/editorconfig-defaults#11]
This is my personal config for markdown: https://github.com/hax/dotfiles/blob/master/src/.editorconfig#L45-L58 

1. Markdown should use `indent_size = 4` as default.
1. For old-style markdown, we may also need `trim_trailing_whitespace = false`, but I don't suggest to add this because it's too bad to rely on illegible trailing spaces.

**Comment by xuhdev** [comment]
Can you make a PR :smile: ?

**Comment by hax** [comment]
PR ready.

Note, after reading CommonMark spec again, I realize `tab_width=4` is much proper than `indent_size=4`, because it is allowed to use both spaces/tabs for indentation.
