### ISSUE TITLE
Change `trim_trailing_spaces` to `trim_trailing_whitespace`

### ISSUE THREAD

**Issue by ryandesign** [editorconfig/editorconfig-defaults#16]
https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/.editorconfig#L7

https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/.editorconfig#L12

Shouldn't `trim_trailing_spaces` rather be `trim_trailing_whitespace`? See:

https://github.com/editorconfig/editorconfig/wiki/Property-research:-Trim-trailing-spaces

**Comment by ryandesign** [comment]
https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/editorconfig-defaults.json#L45

https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/editorconfig-defaults.json#L56

https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/editorconfig-defaults.json#L66

https://github.com/editorconfig/editorconfig-defaults/blob/2686ce43596f0c2c5e5edcf9a3e77bbe171d224d/editorconfig-defaults.json#L98

**Comment by xuhdev** [comment]
Nice catch, thanks!
